sudo: false
language: android

android:
  components:
    - android-22
    - build-tools-23.0.0_rc3
    - build-tools-21.1.2
    - build-tools-21.1.1
    - build-tools-21.0.2
    - build-tools-21.0.1
    - build-tools-19.1.0
    - build-tools-19.0.3
    - build-tools-19.0.0
    - extra-android-support
    - extra-android-m2repository

  licenses:
    - android-sdk-license-5be876d5
env:
  # TERM=dumb : For Gradle build output
  - TERM=dumb

script:
  # Build all gradle-based Android projects
  - cd Android
  - ./build.sh
